title: Byun_Suyoung_profile
description: Full-Stack_Developer
site_title: 'suyoung_profile'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: tndud042713
blog_url: https://tndud042713.github.io/hobby/
email: tndud042713@gmail.com
keybase_username: abhn
twitter_username: abhn_
reddit_username: abhn

# absolute or relative
profile_picture: assets/images/profile-picture.jpg

# Google Analytics ID
google_analytics: 