title: Byun_Suyoung_profile
description: Web & Security Engineer
site_title: '@abhn - Abhishek Nagekar'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: tndud042713
blog_url: https://www.nagekar.com
email: tndud042713@gmail.com
keybase_username: abhn
twitter_username: abhn_
reddit_username: abhn

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 